# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ReactOS.RosBE
PackageVersion: "20261009"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rosbe.exe
  PortableCommandAlias: rosbe
Commands:
- rosbe
ReleaseDate: 2026-10-09
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ahmedarif193/winget-rosbe/releases/download/v20261009/rosbe-bootstrapper-20261009-win-x64.zip
  InstallerSha256: 0B0A5B0DB718D028489A6F0B2FE54E129FDBD8EB36AF1EDBAE8DF9BDEDE74EBB
ManifestType: installer
ManifestVersion: 1.12.0
