# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ReactOS.RosBE
PackageVersion: "20261007"
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: rosbe.exe
  PortableCommandAlias: rosbe
Commands:
- rosbe
ReleaseDate: 2026-10-07
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/ahmedarif193/winget-rosbe/releases/download/v20261007/rosbe-bootstrapper-20261007-win-x64.zip
  InstallerSha256: A250F37CA6408108A4A6C00095088627C5307B5BA6AE0D5ADF23BD077DCD78DE
ManifestType: installer
ManifestVersion: 1.12.0
